### ISSUE TITLE
'Terrein' location

### ISSUE THREAD

**Issue by toonvandeputte** [Fri3dCamp/fri3dcamp-pwa#25]
**Current**
Several activities have 'terrein' as their location, but it is unclear what this entails for users who want to attend (where do they need to go?)

**Expected**
The 'terrein' location has a rallying point on the map or is otherwise explained to users.

**Comment by vdwijngaert** [comment]
Might be a remnant from Sound of Science, "terrein" seems to be hardcoded in some places. To check?

**Comment by toonvandeputte** [comment]
terrein linked to 'buitenpodium'
