### ISSUE TITLE
clickable locations on map

### ISSUE THREAD

**Issue by toonvandeputte** [Fri3dCamp/fri3dcamp-pwa#34]
**Current**
Location labels on map cannot be clicked

**Expected**
Location labels on map can be clicked to show all activities in this location

**Comment by vdwijngaert** [comment]
They can be clicked once the feature is correctly mapped to a location.

Leaves us to decide what to do in case of multiple locations for one map feature / marker, though.

**Comment by toonvandeputte** [comment]
Current solution is OK, but maybe takes up a bit too much space (reduntant titles):


![Image](https://user-images.githubusercontent.com/6859906/183293364-9d98f579-1b20-4afa-ac68-a4a0a1dffa7f.png)
